### ISSUE TITLE
Infra failure when fault or update domain count is changed

### ISSUE THREAD

**Issue by timuthy** [gardener/gardener-extension-provider-azure#109]
**How to categorize this issue?**

/kind bug
/priority normal
/platform azure

**What happened**:
The values `countFaultDomains` or `countUpdateDomains` were changed in a cloud profile. A corresponding shoot had been created successfully with the previous values but when Gardener tried to reconcile the `Infrastructure` of the shoot with the new values, the infra controller failed for the following reason:

```
* compute.AvailabilitySetsClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="Availability Set '<technical-id>' cannot be deleted. Before deleting an Availability Set please ensure that it does not contain any VM."
```

**What you expected to happen**:
The infra should reconcile successfully, probably with the values which had been used to create the Availability Set.

**Comment by timuthy** [comment]
My suggestion is to put the original values for `countFaultDomains` or `countUpdateDomains` into the infrastructure status and use these instead of the ones from the cloud profile.

**Comment by dkistner** [comment]
I like the proposed solution to store the used domain counts in the infrastructure status at least until we have a solution in place which allow us to roll the machines to an updated set which is currently not possible as the set is managed via Terraform and the machines via MCM.

**Comment by vlerenc** [comment]
FYI: Another one reported the issue out-of-band (Slack).

**Comment by pjdurai-altiscale** [comment]
Hi Folks, we are having the issue in the following cluster too:
https://dashboard.garden.live.k8s.ondemand.com/namespace/garden-di-xm8/shoots/dh-fax73yc2mxsc/
