### ISSUE TITLE
Deletion of shoot cluster fails if service allow-udp-egress is pending

### ISSUE THREAD

**Issue by MartinWeindel** [gardener/gardener-extension-provider-azure#169]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority normal
/platform azure

**What happened**:
This was observed on multiple cluster on the canary landscape.
For unknown reasons the load balancer for the shoot service `allow-udp-egress` was not assigned and the service stays in the state pending:
```
> ka get svc
NAMESPACE     NAME               TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
default       kubernetes         ClusterIP      100.64.0.1      <none>        443/TCP          5h6m
kube-system   allow-udp-egress   LoadBalancer   100.71.199.73   <pending>     1234:30593/UDP   3h34m
```

As a consequence the managed resource `extension-controlplane-shoot` is not deleted 

**What you expected to happen**:
The service should be deleted if it is pending

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
Can you share the events of the Service?
I have seen something similar when user deletes the underlying azure resource group. Then the deletion of the azure LB was failing with 404 - this issue is fixed in the upstream with https://github.com/kubernetes/kubernetes/pull/93962.

**Comment by MartinWeindel** [comment]
I did not check for the service events, sorry.

**Comment by ialidzhikov** [comment]
Without logs of cloud-controller-manager or events of the Service itself we cannot proceed with investigation. When the cherry-picks of https://github.com/kubernetes/kubernetes/pull/93962 are merged, I will revendor our cloud-controller-managers.

I am closing this issue right now because of lack of information. Please feel free to reopen when there are more details.

/close
