### ISSUE TITLE
Replace deprecated terraform resources

### ISSUE THREAD

**Issue by timebertt** [gardener/gardener-extension-provider-azure#184]
**How to categorize this issue?**

/area quality
/kind enhancement
/priority normal
/platform azure

**What would you like to be added**:
The deprecated terraform resources `network_security_group_id` and `route_table_id` should be replaced by `azurerm_subnet_network_security_group_association` and `azurerm_subnet_route_table_association` respectively.

**Why is this needed**:
When creating an azure `Infrastructure` terraform gives out the following warnings:
```
Warning: "network_security_group_id": [DEPRECATED] Use the `azurerm_subnet_network_security_group_association` resource instead.

  on tf/main.tf line 24, in resource "azurerm_subnet" "workers":
  24: resource "azurerm_subnet" "workers" {



Warning: "route_table_id": [DEPRECATED] Use the `azurerm_subnet_route_table_association` resource instead.

  on tf/main.tf line 24, in resource "azurerm_subnet" "workers":
  24: resource "azurerm_subnet" "workers" {
```

**Comment by ialidzhikov** [comment]
They should exist both until we upgrade our terraform-provider-azurerm to v2.0.0. We already had a major issue when we removed them in the past.

**Comment by dkistner** [comment]
Yep this is already in preparation.
/assign

**Comment by ialidzhikov** [comment]
@dkistner , can be this closed after https://github.com/gardener/gardener-extension-provider-azure/pull/192, right?
