### ISSUE TITLE
Azure loadbalancers cannot be created

### ISSUE THREAD

**Issue by schrodit** [gardener/gardener-extension-provider-azure#2]
Azure shoots cannot be provisioned sometimes because the cloud controller manager is unable to create the vpn and nginx loadbalancer.

The cloud controller managers states that the corresponding public IP address cannot be found
```
Error syncing load balancer: failed to ensure load balancer: Code="ReferencedResourceNotProvisioned" 
Message="Cannot proceed with operation because resource /subscriptions/xxx/resourceGroups/shoot-az-xxx/providers/Microsoft.Network/publicIPAddresses/shoot-az-xxx--abc used by resource /subscriptions/xxx/resourceGroups/shoot-az-xxx/providers/Microsoft.Network/loadBalancers/shoot-az-xxx is not in Succeeded state. 
Resource is in Failed state and the last operation that updated/is updating the resource is PutPublicIpAddressOperation
```

The issue is looks like a inconsistency in azure.

### Steps to reproduce
- create a azure shoot with nginx addon enabled.

The issue can be resolved by deleting both services which then triggers the deletion the loadbalancer.
After the reconcilition the loadbalancer is then created successfully.

**Comment by rfranzke** [comment]
I'm closing this issue now as it has no progress and no clear steps to reproduce. Kindly reopen with more information if you still observe this problem.
