### ISSUE TITLE
Cannot delete last LoadBalancer service when using VMO

### ISSUE THREAD

**Issue by kon-angelo** [gardener/gardener-extension-provider-azure#374]
**How to categorize this issue?**

/area control-plane
/kind bug
/priority 3
/platform azure

**What happened**:

Deleting the last loadbalancer service will fail with error:

```
  Warning  SyncLoadBalancerFailed   3m27s (x11 over 6m35s)  service-controller               Error syncing load balancer: failed to delete load balancer: not a vmss instance
```

**What you expected to happen**:

For the service to be deleted

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a VMO cluster
2. Create a new service of type loadbalancer
3. Try to delete the service.

Be mindful, that if the shoot is not using the reverse VPN tunneling, then the "last" service will be the _vpn-shoot_ service. In that case the skip step 2 and the_vpn-shoot_ service should be deleted 

**Anything else we need to know?**:

The error seems to not be reproducible with the latest `cloud-provider-azure` version (v1.1.1). Solving https://github.com/gardener/gardener-extension-provider-azure/issues/373 is a potential mitigation.  

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.21.x
- Kubernetes version (use `kubectl version`): 1.21.x
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
Ref https://github.com/kubernetes/kubernetes/pull/105185 (credits to @kon-angelo)
