### ISSUE TITLE
When NAT Gateway is enabled, public IP should be removed from the VM

### ISSUE THREAD

**Issue by jia-jerry** [gardener/gardener-extension-provider-azure#393]
**How to categorize this issue?**

/area networking
/kind enhancement
/priority 3
/platform azure

**What would you like to be added**:
When NAT Gateway is enabled in a shoot, all VMs don't need public IPs anymore. https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#scenarios

**Why is this needed**:

**Comment by dkistner** [comment]
Hi @jia-jerry,

not sure if I got it correctly, but we don't add any public ips directly to the nodes.

I see one improvement to be done if a cluster has a Nat Gateway enabled. ref https://github.com/gardener/gardener-extension-provider-azure/issues/293

**Comment by dkistner** [comment]
This can be closed. There are no dedicated public ips assigned to machines directly.
/close
