### ISSUE TITLE
Gardenlet to project a service account token into the Seed for IaaS authentication purposes 

### ISSUE THREAD

**Issue by donistz** [gardener/gardener-extension-provider-azure#400]
**How to categorize this issue?**

/area security
/kind enhancement

**What would you like to be added**:
Gardenlet to project a service account token or centrally managed SPN secret into the Seed for IaaS authentication purposes 
**Why is this needed**:
In order Gardener to start supporting this scenario:
- Enable alternative authentication method for "Azure secret configuration" by using a default (centrally managed) SPN per Azure Directory (Tenant) ID for managing consumer IaaS resources as described in the issue https://github.com/gardener/gardener-extension-provider-azure/issues/383

**gardenlet** has to be extended to support the following scenario:
- `gardenlet` to check for refreshed centrally managed Azure SPNs and to update it in the Seed cluster so that the Azure extension provider can find it and use it for authentication to the Azure APIs

**Comment by vlerenc** [comment]
@donistz See above, as written in the first comment, the `gardenlet` is provider-agnostic.

@donistz cc @rfranzke See above, as written in the first comment, why are we duplicating what @dkistner already described  after our call in https://github.com/gardener/gardener-extension-provider-azure/issues/383#issuecomment-950810773. What are the differences in the tickets? I am getting lost here. Even "more tickets" are **not** "more helpful".

**Comment by donistz** [comment]
@rfranzke Hi Rafael, I close the ticket because according to what is planned to be implemented with #383 (comment) as mentioned by Vedran, there will be no need to change the gardenlet logic. There is a change planned in the `ControllerDeployment `resource that will be detected and used by the gardenlet.
