### ISSUE TITLE
Define what privileges are needed for the Azure ServicePrincipal

### ISSUE THREAD

**Issue by dansible** [gardener/gardener-extension-provider-azure#44]
**What would you like to be added**:

In the [usage-as-end-user](https://github.com/gardener/gardener-extension-provider-azure/blob/master/docs/usage-as-end-user.md#provider-secret-data) document, it states that an Azure `ServicePrincipal` is required for creating shoot clusters. Would it be possible to define the minimum roles needed for this user to create shoots in Azure? 

**Why is this needed**:

We are currently using the `Contributer` role but this is likely over privileged for what is needed

**Comment by rfranzke** [comment]
Duplicate/related to #26 ?

**Comment by dansible** [comment]
Ah yes thanks @rfranzke 👍 

Will just comment the other issue to have the resulting role be documented
