### ISSUE TITLE
Accelerated Network Enablement

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener-extension-provider-azure#55]
**What would you like to be added**:
Azure supports a feature called Accelerated Networking to increase network performance of virtual machines e.g. reduce latency/more packet per second, lower cpu utilization.
The usage of the feature depends on the machine type and the operating systems.
More information are available [here](https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli).

**Why is this needed**:
This feature comes for free and should therefore be enabled  by default for all machines and os images combinations which support it.

To enable the feature we just need to turn on a flag on the network interfaces attached to the vm (see [here](https://github.com/Azure/azure-sdk-for-go/blob/master/services/network/mgmt/2019-11-01/network/models.go#17582)).

We would need to put the information which machine type and os image support accelerated networking into the Azure specific part of the CloudProfile. The supported machine types can be fetched via an Azure api (e.g. `az vm list-skus`) and therefore it can be automated.
The operating systems need to be maintained manually. A list is of supported ones is available [here](https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli#supported-operating-systems).
Custom images are also supported but there are some requirements, see [here](https://docs.microsoft.com/en-us/azure/virtual-network/create-vm-accelerated-networking-cli#custom-images).

**Action Items**
- [x] MCM need to support creating machine with network interfaces that have accelerated networking enabled.
- [ ] Gardener Azure Provider need to render and deploy proper machine classes
- [ ] Gardener Azure CloudProfile need to be extended to allow to configure accelerated networking supporting machine types and operating systems

Automate CloudProfile creation wherever possible by using the Azure apis.

**Comment by dkistner** [comment]
Azure has a validation to check if the machine type does support accelerated networking, therefore I think there is no need to add the machine types which support it in the CloudProfile. In case the user enable accelerated networking and choose an incompatible machine type the error will be transparently reported to the user.
For supported operating systems I need to check if there is also a validation. I assume not and we should then add accelerated networking supported os in the cloud profile to prevent machine without network connectivity.

**Comment by rfranzke** [comment]
Fixed with https://github.com/gardener/gardener-extension-provider-azure/commit/357a30d0377385e0bd6f65bd57ee8c0287101d26
