### ISSUE TITLE
guestbook test is failing on Azure for multi-zone clusters

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-azure#610]
**How to categorize this issue?**

/area storage
/kind bug
/platform azure

**What happened**:
```
$ go test -timeout=0 -mod=vendor ./test/testmachinery/suites/shoot \
--v -ginkgo.v -ginkgo.progress -ginkgo.no-color \
--report-file=/tmp/report.json \
-kubecfg=$KUBECONFIG \
-shoot-name=$SHOOT_NAME \
-project-namespace=$SHOOT_NAMESPACE \
-ginkgo.focus="\[RELEASE\]" \
-ginkgo.skip="\[SERIAL\]|\[DISRUPTIVE\]"
```

The redis Pod cannot be created with:
```
$ k -n gardener-e2e-z44wn describe po redis-master-0

  Warning  FailedAttachVolume  105s (x8 over 3m56s)  attachdetach-controller  AttachVolume.Attach failed for volume "pv-shoot--foo--testy-9d4a6cd3-7c80-43bf-bd97-2b63ada8c05d" : rpc error: code = Internal desc = update instance "shoot--foo--testy-worker-1-z1-6cf8c-q2jv5" failed with Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: Code="PropertyChangeNotAllowed" Message="Changing property 'imageReference' is not allowed.  Target: 'imageReference'."
```

**What you expected to happen**:
The guestbook test to be successful for multi-zone clusters.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.32.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by kon-angelo** [comment]
/close

This issue was patched from the Azure side and should no longer be occuring.
