### ISSUE TITLE
Change StorageAccount for backupbucket from LRS to ZRS

### ISSUE THREAD

**Issue by unmarshall** [gardener/gardener-extension-provider-azure#777]
**How to categorize this issue?**
/area control-plane
/area high-availability
/kind enhancement
/platform azure

**What would you like to be added**:
Currently `StorageAccount` that is created is of type `StandardLRS` which is described [here](https://learn.microsoft.com/en-us/azure/storage/common/storage-redundancy?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json#locally-redundant-storage).  An excerpt from the link which is of relevance:

This storage account SKU is then used to create the storage account for backup-bucket [here](https://github.com/gardener/gardener-extension-provider-azure/blob/master/pkg/controller/backupbucket/backupbucket.go#L51). This backup-bucket is then used by etcd to store backups (full and delta snapshots) which are essential for restoration of the etcd cluster.

**Why is this needed**:
Change to ZRS would help in adding resiliency in case zonal failures.
> NOTE: 
>--------------------------------------------------------------------------------------------------------------
>- Care should be taken when making this change as impact on existing storage accounts needs to be carefully examined. See [limitations on changing storage account types](https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal#limitations-for-changing-replication-types).
>- There will be an impact on the cost as well. See [here](https://azure.microsoft.com/en-us/pricing/details/storage/blobs/) for more details.

**Comment by kon-angelo** [comment]
Should be fixed with https://github.com/gardener/gardener-extension-provider-azure/pull/790
