### ISSUE TITLE
Enable Serial Console Support in Worker Node 

### ISSUE THREAD

**Issue by YakovKugel** [gardener/gardener-extension-provider-azure#786]
**How to categorize this issue?**

/area monitoring
/kind enhancement
/platform azure

**What would you like to be added**:
We would like Gardener to enable serial console from each worker node (VMs ) in Azure.
Currently serial console access is unavailable even with correct CAM permission.   

**Why is this needed**:

The serial console would allow easier debug/operational process and would significantly decrease development time.

**Comment by YakovKugel** [comment]
Adding @i548745

**Comment by kon-angelo** [comment]
@YakovKugel please be careful with use of internal IDs in the public github.

Regarding the feature, the main problem is that per https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/serial-console-linux#prerequisites you need to have a password-based user. That has quite a few security implications and most of the images in our landscapes do not support such users.

What this means is that if you want to use this feature to debug actual boot issues with the nodes, you need another mechanism to introduce a way of configuring password-based users and the provider extension is not the place for that (it involves gardener core, the OS teams etc.).

If we were to introduce it without any the other gardener change I mentioned, it would basically "tick" the boxes in the VMs that would allow the serial console and you would need to use some payload mechanism like "custom" daemon sets to create your own password-based user on the nodes to be able to actually use the feature. It also prerequisites tha the node has joined the cluster which makes it useless for debugging boot issues.

**Comment by ZionChen01** [comment]
Hello @kon-angelo 

Just to clear our request. 
we don't ask to enable Console login to the instance. we don't want to debug actual boot issue from the console. 
what we ask, is to be able to see the boot process in the serial log. the name of serial log in Azure portal is  "serial console"

![image](https://github.com/gardener/gardener-extension-provider-azure/assets/88369658/21a61b6c-30b0-426e-901b-ff99d65dda4a)
