### ISSUE TITLE
Cannot delete `BackupEntries` which use the secret from a `core.BackupBucket.status.generatedSecretRef` reference

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardener-extension-provider-azure#793]
**How to categorize this issue?**

/kind bug
/platform azure

**What happened**:
Currently it is not possible to delete `extensions.BackupEntries` which have the following data in the secret specified by their `.spec.secretRef` field:
```
data:
  storageAccount: <account>
  storageKey: <key>
```

Trying to delete such a `BackupEntry` returns the following error:
```
'Error deleting BackupEntry: secret garden/entry-<backup-entry-name>
      doesn''t have a subscription ID'
```

**What you expected to happen**:
`extensions.BackupEntries` to be deleted successfully

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a shoot cluster with provider azure
2. Delete the shoot cluster
3. Make sure that the `core.BackupEntry` for the shoot is deleted as well - the grace period for it's deletion should be 0 or it should be manually deleted
4. Observe that the `core.BackupEntry` deletion fails, because its associated `extensions.BackupEntry` cannot be deleted with: 
    ```
    'Error deleting BackupEntry: secret garden/entry-<backup-entry-name>
          doesn''t have a subscription ID'
    ```
**Anything else we need to know?**:
The problem seems to come from this validation: 
https://github.com/gardener/gardener-extension-provider-azure/blob/5c5b346ca2eae56030768e2cf2d2ef92ba732d49/pkg/internal/auth.go#L69-L72

This code is called when instantiating a factory which is then used to get an azure storage client to delete the backup object associated with the `extensions.BackupEntry` here:
https://github.com/gardener/gardener-extension-provider-azure/blob/5c5b346ca2eae56030768e2cf2d2ef92ba732d49/pkg/controller/backupentry/actuator.go#L46-L50
https://github.com/gardener/gardener-extension-provider-azure/blob/5c5b346ca2eae56030768e2cf2d2ef92ba732d49/pkg/azure/client/factory.go#L38-L42
https://github.com/gardener/gardener-extension-provider-azure/blob/5c5b346ca2eae56030768e2cf2d2ef92ba732d49/pkg/internal/auth.go#L50-L56

So this actually expects the data in the secret reference to be of the following format:
```
data:
  clientID: <client-id>
  clientSecret: <client-secret>
  subscriptionID: <subscription-id>
  tenantID: <tenant-id>
```

--- 
Previously (before https://github.com/gardener/gardener-extension-provider-azure/pull/739) we did not use the secret reference when instantiating a factory for the azure client:
https://github.com/gardener/gardener-extension-provider-azure/blob/417843d6dd5bf024930a32a8852d87e11b292827/pkg/controller/backupentry/actuator.go#L48-L49
https://github.com/gardener/gardener-extension-provider-azure/blob/417843d6dd5bf024930a32a8852d87e11b292827/pkg/azure/client/factory.go#L32-L36

Instantiating only the storage client with the secret ref was ok, because the storage client actually only needs the data that is already present in the secret:
```
data:
  storageAccount: <account>
  storageKey: <key>
```

---

Essentially there are two different types of provider auth secret data:
(1):
```
data:
  storageAccount: <account>
  storageKey: <key>
```
and (2)
```
data:
  clientID: <client-id>
  clientSecret: <client-secret>
  subscriptionID: <subscription-id>
  tenantID: <tenant-id>
```

The secret data in (1) is inside the secret specified in the `core.BackupBucket.status.generatedSecretRef` field, whereas the secret data in (2) is inside the secret specified in the `core.BackupBucket.spec.secretRef` field.
When a `core.BackupEntry` is reconciled, the `BackupEntry` controller in gardenlet checks if the corresponding `core.BackupBucket` has a `.status.generatedSecretRef` field, and if that is the case, it will copy the corresponding secret to the seed cluster and set that as the `extensions.BackupEntry.spec.secretRef`.
If a `.status.generatedSecretRef` field does not exist, the `BackupEntry` controller will instead copy the `core.BackupBucket.spec.secretRef` to the seed cluster and set that to the `extensions.BackupEntry.spec.secretRef` field.
This can be seen in the following code:
https://github.com/gardener/gardener/blob/cff77d588fa928a950ce1459f2c856a2d9bee2e9/pkg/gardenlet/controller/backupentry/reconciler.go#L651-L663
https://github.com/gardener/gardener/blob/cff77d588fa928a950ce1459f2c856a2d9bee2e9/pkg/gardenlet/controller/backupentry/reconciler.go#L170-L173
https://github.com/gardener/gardener/blob/cff77d588fa928a950ce1459f2c856a2d9bee2e9/pkg/gardenlet/controller/backupentry/reconciler.go#L332-L339
https://github.com/gardener/gardener/blob/cff77d588fa928a950ce1459f2c856a2d9bee2e9/pkg/gardenlet/controller/backupentry/reconciler.go#L665-L675

---

**Environment**:

- Gardener version (if relevant):
- Extension version: `v1.41.1` however it should be present since `v1.40.0`
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by ialidzhikov** [comment]
@kon-angelo can we close this issue after https://github.com/gardener/gardener-extension-provider-azure/pull/795 is merged?

**Comment by kon-angelo** [comment]
@ialidzhikov This should be closed yes
