### ISSUE TITLE
Map context timeout/deadline exceeded code during VM Deletion to gardener ERR_INFRA_DEPENDENCIES

### ISSUE THREAD

**Issue by elankath** [gardener/gardener-extension-provider-azure#839]
**How to categorize this issue?**

/area monitoring
/kind enhancement
/platform azure

**What would you like to be added**:
Ensure that when VM deletion in Azure fails due to deadline exceeded, the shoot object health check under `Type: EveryNodeReady` has the gardener high level error code: `ERR_INFRA_DEPENDENCIES`

Dependent Issue on MCM azure has also been created at: https://github.com/gardener/machine-controller-manager-provider-azure/issues/147

**Why is this needed**:

This will address overload of alerts.
See gardener landscape live issue: 125 for further details

**Comment by rishabh-11** [comment]
/close

based on comment on landscape issue 125
