### ISSUE TITLE
Can't use azure dns provider with non-azure infrastructure provider

### ISSUE THREAD

**Issue by j2L4e** [gardener/gardener-extension-provider-azure#859]
/area control-plane
/kind regression
/platform azure

**What happened**:
We run shoots on hetzner cloud. Since hetzner doesn't support managing dns, we use the azure-extension to handle dnsrecords for hcloud shoots.
Since #815 the dnsrecord reconciler throws errors because it can't decode a non-azure cloudprofile's providerConfig:

```
could not decode providerConfig of cloudProfile for 'hcloud': no kind "CloudProfileConfig" is registered for version "hcloud.provider.extensions.gardener.cloud/v1alpha1" in scheme 

sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.3/pkg/internal/controller/controller.go:227
```

**What you expected to happen**:
The extension should reconcile dnsrecords.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a non-azure shoot.
- Add an azure-dns dns provider
- Create a dns-record for that provider

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant): 1.94
- Extension version: 1.43.1
- Kubernetes version (use `kubectl version`): 1.28.9
- Cloud provider or hardware configuration: azure/hcloud

**Comment by kon-angelo** [comment]
Hello @j2L4e. Issue acknowledged, we will try to get a fix going asap.
