### ISSUE TITLE
Blocks of type "timeouts" are not expected here

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-azure#88]
**What happened**:
Infrastructure fails with `Blocks of type "timeouts" are not expected here`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create Shoot.

2. Ensure that the Infrastructure reconciliation fails with:
```
$ k -n shoot--foo--bar logs bar.infra.tf-apply-nbk4c -f
Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.azurerm: version = "~> 1.44"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Error: Unsupported block type

  on tf/main.tf line 12, in resource "azurerm_resource_group" "rg":
  12:   timeouts {

Blocks of type "timeouts" are not expected here.


Nothing to do.
Tue May 19 09:47:47 UTC 2020 terraform.sh exited with 0.
```
**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
https://www.terraform.io/docs/providers/azurerm/r/resource_group.html#timeouts states that timeouts are allowed. Probably our AzureRM version is too old?

**Comment by ialidzhikov** [comment]
Yeah. The terraform docs as not versioned.

**Comment by rfranzke** [comment]
cc @dkistner @AndreasBurger - an integration test similar to https://github.com/gardener/gardener-extension-provider-aws/pull/54 would increase the DEV productivity tremendously...
