### ISSUE TITLE
Enable Assignment of Existing NAT Gateway to Shoot Subnet

### ISSUE THREAD

**Issue by fgksteinman** [gardener/gardener-extension-provider-azure#968]
**How to categorize this issue?**
/area networking
/kind enhancement
/platform azure

**What would you like to be added**:
In Azure, a NAT Gateway gets associated to a VNet, and can be enabled on a subnet-by-subnet basis for that VNet.
My team deploys multiple shoot clusters into a single VNet, using shoot-specific subnets created by Gardener, and would like Gardener to support assigning an existing NAT gateway to each cluster's subnet by updating the cluster's shoot spec.

**Why is this needed**:
We have been updating (manually / outside of the gardener shoot spec) these subnets to associate a shared NAT gateway, and this was working until the release of https://github.com/gardener/gardener-extension-provider-azure/pull/945. Subnet reconciliation is now removing the NAT Gateway association.
We require static/shared NAT IPs because the NAT IPs are allowlisted on firewalls for internal management/administrative endpoints and also allowlisted by customers for their integrations. It is not reasonable for us to ask customers and internal systems to update firewall rules every time a new shoot is created.

**Comment by vpnachev** [comment]
fixed by #978 

/close
